# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Vinay Mundada
tagline:          'My Tech Blog'
description:      'Sharing Tech with the world...'
url :             https://vinaymundada27.github.io
# baseurl:          /

author:
    name  :           'Vinay Mundada'
    email :            vinaymundada27@gmail.com
    url   :            https://www.linkedin.com/in/vinaymundada27/

paginate:         5

# Custom vars
github:
    repo  :           https://github.com/vinaymundada27/vinaymundada27.github.io
    url   :           https://github.com/vinaymundada27

plugins :         [jekyll-paginate, jekyll-gist, jekyll-coffeescript]
