# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Tech Blog
tagline:          'Coming Soon...'
description:      '...'
url:              https://vinaymundada27.github.io
baseurl:          /

author:
  name:           'Vinay Mundada'
  url:            https://www.linkedin.com/in/vinaymundada27/

paginate:         5

# Custom vars
github:           https://github.com/vinaymundada27/vinaymundada27
  repo:           https://github.com/vinaymundada27/vinaymundada27.github.io

plugins :         [jekyll-paginate, jekyll-gist, jekyll-coffeescript]
