# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Vinay Mundada
tagline:          'My Tech Blog'
description:      'Coming Soon...'
# url:              http://hyde.getpoole.com
url :             https://vinaymundada27.github.io
baseurl:          /

author:
name  :           'Vinay Mundada'
url   :            https://www.linkedin.com/in/vinaymundada27/

paginate:         1

# Custom vars
github:           https://github.com/vinaymundada27
  repo:           https://github.com/vinaymundada27/vinaymundada27.github.io

plugins :         [jekyll-paginate, jekyll-gist, jekyll-coffeescript]